export const messages = [
  { text: 'A vida trará coisas boas se tiver paciência.' },
  { text: 'Demonstre amor e alegria em todas as oportunidades e verá que a paz nasce dentro de si.' },
  { text: 'Não compense na ira o que lhe falta na razão.' },
  { text: 'Defeitos e virtudes são apenas dois lados da mesma moeda.' },
  { text: 'A maior de todas as torres começa no solo.' },
  { text: 'Não há que ser forte. Há que ser flexível.' },
  { text: 'Todos os dias organiza os seus cabelos, por que não faz o mesmo com o coração?' },
  { text: 'Há três coisas que jamais voltam; a flecha lançada, a palavra dita e a oportunidade perdida.' },
  { text: 'A juventude não é uma época da vida, é um estado de espírito.' },
  { text: 'Podemos escolher o que semear, mas somos obrigados a colher o que plantamos.' },
  { text: 'Dê toda a atenção á formação dos seus filhos, sobretudo com bons exemplos da sua própria vida.' },
  { text: 'Siga os bons e aprenda com eles.' },
  { text: 'Não importa o tamanho da montanha, ela não pode tapar o sol.' },
  { text: 'O bom-senso vale mais do que muito conhecimento.' },
  { text: 'Quem quer colher rosas tem de estar preparado para suportar os espinhos.' },
  { text: 'São os nossos amigos que nos ensinam as mais valiosas lições.' },
  { text: 'Aquele que se importa com o sentimento dos outros, não é um tolo.' },
  { text: 'A adversidade é um espelho que reflete o verdadeiro eu.' },
  { text: 'Lamentar aquilo que não temos é desperdiçar aquilo que já possuímos.' },
  { text: 'Uma bela flor é incompleta sem as suas folhas.' },
  { text: 'Sem o fogo do entusiasmo, não há o calor da vitória.' },
  { text: 'O riso é a menor distância entre duas pessoas.' },
  { text: 'Os defeitos são mais fortes quando o amor é fraco.' },
  { text: 'Amizade e Amor são coisas que se unem num piscar de olhos.' },
  { text: 'Surpreender e ser surpreendido é o segredo do amor.' },
  { text: 'Faça pequenas coisas hoje e coisas maiores lhe serão confiadas amanhã.' },
  { text: 'A paciência na adversidade é sinal de um coração sensível.' },
  { text: 'A sorte favorece a mente bem preparada.' },
  { text: 'A sua visão se tornará mais clara apenas quando conseguir olhar para dentro do seu coração.' },
  { text: 'Quem olha para fora sonha; quem olha para dentro acorda.' },
  { text: 'As pessoas esquecerão o que você disse e o que você fez… mas nunca esquecerão como se sentiram.' },
  { text: 'Espere pelo mais sábio dos conselhos: o tempo.' },
  { text: 'Todas as coisas são difíceis antes de se tornarem fáceis.' },
  { text: 'Se você se sente só é porque construiu muros ao invés de pontes.' },
  { text: 'Vencer é 90 por cento suor e 10 por cento de engenho.' },
  { text: 'O amor está sempre mais próximo do que você imagina.' },
  { text: 'Você é do tamanho do seu sonho.' },
  { text: 'Pare de procurar eternamente; a felicidade está mesmo aqui ao seu lado.' },
  { text: 'O conhecimento é a única virtude e a ignorância é o único vício.' },
  { text: 'O nosso primeiro e último amor é… o amor-próprio.' },
  { text: 'Deixe de lado as preocupações e seja feliz.' },
  { text: 'A vontade das pessoas é a melhor das leis.' },
  { text: 'Nós somos o que pensamos.' },
  { text: 'A maior barreira para o sucesso é o medo do fracasso.' },
  { text: 'O pessimista vê a dificuldade em cada oportunidade; O otimista vê a oportunidade em cada dificuldade.' },
  { text: 'Muitas das grandes realizações do mundo foram feitas por homens cansados e desanimados que continuaram o seu trabalho.' },
  { text: 'O insucesso é apenas uma oportunidade para recomeçar de novo com mais experiência.' },
  { text: 'Coragem é a resistência ao medo, domínio do medo, e não a ausência do medo.' },
  { text: 'O verdadeiro homem mede a sua força, quando se defronta com o obstáculo.' },
  { text: 'Quem quer vencer um obstáculo deve armar-se da força do leão e da prudência da serpente.'},
  { text: 'A adversidade desperta em nós capacidades que, em circunstâncias favoráveis, teriam ficado adormecidas.' },
  { text: 'Motivação não é sinónimo de transformação, mas um passo em sua direção.' },
  { text: 'O que empobrece o ser humano, não é a falta de dinheiro, mais sim, a falta de fé,motivação e criatividade.' },
  { text: 'A inspiração vem dos outros. A motivação vem de dentro de nós.' },
  { text: 'Não acredite mais em pessoas especiais, mas em momentos especiais com pessoas normais.' },
  { text: 'A nossa vida tem 4 sentidos… Amar, Sofrer, Lutar e Vencer. Ame muito, sofra pouco, lute bastante e vença sempre!' },
  { text: 'Nada é por acaso… Acredite em seus sonhos e nos seus potenciais….Na vida tudo se supera..' },
  { text: 'Acredite em milagres, mas não dependa deles.' },
  { text: 'Você sempre será a sua melhor companhia!' },
  { text: 'Realize o óbvio, pense no improvável e conquiste o impossível.' },
];
